-- MySQL Script generated by MySQL Workbench
-- Fri Jun 18 18:29:26 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BuyIt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BuyIt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BuyIt` DEFAULT CHARACTER SET utf8 ;
USE `BuyIt` ;

-- -----------------------------------------------------
-- Table `BuyIt`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyIt`.`Clientes` (
  `idCliente` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(8) NOT NULL,
  `direccion` VARCHAR(200) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuyIt`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyIt`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(300) NOT NULL,
  `telefono` VARCHAR(8) NOT NULL,
  `fecha_admision` DATETIME NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `Clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Clientes1_idx` (`Clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_Clientes1`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `BuyIt`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuyIt`.`Proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyIt`.`Proveedores` (
  `idProveedores` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(12) NOT NULL,
  `direccion` VARCHAR(200) NULL,
  PRIMARY KEY (`idProveedores`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuyIt`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyIt`.`Productos` (
  `idProducto` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` DECIMAL(2) NOT NULL,
  `costo` DECIMAL(2) NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuyIt`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyIt`.`Categories` (
  `idCategory` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `Productos_idProducto` INT NOT NULL,
  PRIMARY KEY (`idCategory`, `Productos_idProducto`),
  INDEX `fk_Categories_Productos1_idx` (`Productos_idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Categories_Productos1`
    FOREIGN KEY (`Productos_idProducto`)
    REFERENCES `BuyIt`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuyIt`.`tipoDePago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyIt`.`tipoDePago` (
  `idPayment_type` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPayment_type`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuyIt`.`Recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyIt`.`Recibo` (
  `idRecibo` INT NOT NULL,
  `subtotal` DECIMAL(2) NOT NULL,
  `isv` DECIMAL(2) NOT NULL,
  `payment_type` INT NOT NULL,
  `Clientes_idCliente` INT NOT NULL,
  PRIMARY KEY (`idRecibo`),
  INDEX `fk_Bills_Payment_types_idx` (`payment_type` ASC) VISIBLE,
  INDEX `fk_Recibo_Clientes1_idx` (`Clientes_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Bills_Payment_types`
    FOREIGN KEY (`payment_type`)
    REFERENCES `BuyIt`.`tipoDePago` (`idPayment_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recibo_Clientes1`
    FOREIGN KEY (`Clientes_idCliente`)
    REFERENCES `BuyIt`.`Clientes` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuyIt`.`Recibo_has_Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyIt`.`Recibo_has_Productos` (
  `Recibo_idRecibo` INT NOT NULL,
  `Productos_idProducto` INT NOT NULL,
  PRIMARY KEY (`Recibo_idRecibo`, `Productos_idProducto`),
  INDEX `fk_Recibo_has_Productos_Productos1_idx` (`Productos_idProducto` ASC) VISIBLE,
  INDEX `fk_Recibo_has_Productos_Recibo1_idx` (`Recibo_idRecibo` ASC) VISIBLE,
  CONSTRAINT `fk_Recibo_has_Productos_Recibo1`
    FOREIGN KEY (`Recibo_idRecibo`)
    REFERENCES `BuyIt`.`Recibo` (`idRecibo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Recibo_has_Productos_Productos1`
    FOREIGN KEY (`Productos_idProducto`)
    REFERENCES `BuyIt`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuyIt`.`Proveedores_has_Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyIt`.`Proveedores_has_Productos` (
  `Proveedores_idProveedores` INT NOT NULL,
  `Productos_idProducto` INT NOT NULL,
  PRIMARY KEY (`Proveedores_idProveedores`, `Productos_idProducto`),
  INDEX `fk_Proveedores_has_Productos_Productos1_idx` (`Productos_idProducto` ASC) VISIBLE,
  INDEX `fk_Proveedores_has_Productos_Proveedores1_idx` (`Proveedores_idProveedores` ASC) VISIBLE,
  CONSTRAINT `fk_Proveedores_has_Productos_Proveedores1`
    FOREIGN KEY (`Proveedores_idProveedores`)
    REFERENCES `BuyIt`.`Proveedores` (`idProveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proveedores_has_Productos_Productos1`
    FOREIGN KEY (`Productos_idProducto`)
    REFERENCES `BuyIt`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuyIt`.`Lote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyIt`.`Lote` (
  `idLote` INT NOT NULL,
  `FechaDeLote` DATE NOT NULL,
  PRIMARY KEY (`idLote`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BuyIt`.`Lote_has_Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BuyIt`.`Lote_has_Productos` (
  `Lote_idLote` INT NOT NULL,
  `Productos_idProducto` INT NOT NULL,
  PRIMARY KEY (`Lote_idLote`, `Productos_idProducto`),
  INDEX `fk_Lote_has_Productos_Productos1_idx` (`Productos_idProducto` ASC) VISIBLE,
  INDEX `fk_Lote_has_Productos_Lote1_idx` (`Lote_idLote` ASC) VISIBLE,
  CONSTRAINT `fk_Lote_has_Productos_Lote1`
    FOREIGN KEY (`Lote_idLote`)
    REFERENCES `BuyIt`.`Lote` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lote_has_Productos_Productos1`
    FOREIGN KEY (`Productos_idProducto`)
    REFERENCES `BuyIt`.`Productos` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
